from pathlib import Path
import json

GTAG='''<!-- Google tag (gtag.js) --><script async src="https://www.googletagmanager.com/gtag/js?id=G-SXWZ2Z96S9"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-SXWZ2Z96S9');gtag('config','AW-17972657888');</script>'''
CSS='''<link rel="stylesheet" href="/styles.css?v=20260903-regional" /><link rel="stylesheet" href="/assets/css/modern-header.css?v=20260804-2" /><link rel="stylesheet" href="/assets/css/core-location-v3.css?v=20260903" /><link rel="stylesheet" href="/assets/css/regional-child-v3.css?v=20260903" />'''

PAGES=[
{
'path':'service-areas/clay-county/fleming-island.html','slug':'fleming-island','parent':'Clay County','parent_url':'/service-areas/clay-county','name':'Fleming Island','title':'Fleming Island Paver Sealing | Driveways, Pool Decks & Patios | HydroSeal','desc':'Fleming Island paver sealing for established driveways, patios and pool decks with shade, humidity, irrigation and joint-sand wear.','image':'/assets/hero/fleming-island-paver-sealing-driveway.webp','layout':'split','eyebrow':'Fleming Island • Clay County','h1':'Paver Sealing for Established Fleming Island Hardscapes','intro':'Fleming Island properties often combine mature landscaping, waterfront-adjacent humidity, irrigation, screened pool decks and broad paver driveways. HydroSeal evaluates how shade, moisture and previous maintenance have affected the surface before choosing the cleaning, joint-restoration and sealing scope.','areas':['Fleming Island','Clay County'],
'features':[('Waterfront humidity','Moisture can linger longer around shaded or landscaped hardscapes, especially after summer storms.'),('Mature landscaping','Tree canopy, leaf tannins and irrigation can create dark buildup that must be removed before sealing.'),('Large driveways','Broad visible surfaces make joint consistency, runoff and even sealer coverage especially important.'),('Pool environments','Screen enclosures, splash-out and shade create a different moisture pattern from the front driveway.')],
'faq':[('Why do Fleming Island pavers get dark in shaded areas?','Mature landscaping can keep pavers damp longer after rain or irrigation. That supports organic growth and darker joint lines, especially near beds, pool enclosures and shaded driveway edges.'),('Do you replace joint sand before sealing in Fleming Island?','When joint restoration is part of the scope, HydroSeal cleans first and restores low joints with kiln-dried ASTM C144 sand before sealing.'),('Can you seal pool decks in Fleming Island?','Yes. Suitable paver pool decks are evaluated separately from driveways because moisture, shade and foot traffic affect preparation and cure planning.'),('What if my pavers were sealed before?','We inspect remaining coating condition and compatibility before another system is applied. Worn but sound coatings may be resealing candidates; failed coatings can require a heavier restoration path.')],
'siblings':[('Orange Park','/service-areas/clay-county/orange-park'),('Oakleaf Plantation','/service-areas/clay-county/oakleaf-plantation'),('Middleburg','/service-areas/clay-county/middleburg')]
},
{
'path':'service-areas/clay-county/orange-park.html','slug':'orange-park','parent':'Clay County','parent_url':'/service-areas/clay-county','name':'Orange Park','title':'Orange Park Paver Sealing | Driveways, Patios & Pool Decks | HydroSeal','desc':'Orange Park paver sealing for older shaded driveways, patios and pool decks with mildew, staining, joint loss and previous sealer wear.','image':'/assets/hero/orange-park-paver-sealing-driveway.webp','layout':'cover','eyebrow':'Orange Park • Clay County','h1':'Restore Older Orange Park Pavers Before Another Coat Goes Down','intro':'Orange Park has many established properties where shade, mature trees, irrigation and years of prior maintenance create a different job than a new installation. HydroSeal starts with the existing condition—staining, joint depth, drainage and old sealer—before deciding whether the project is cleaning, resealing or a deeper restoration.','areas':['Orange Park','Clay County'],
'features':[('Older installations','Mixed-age pavers, repairs and previous coatings can change what a compatible restoration requires.'),('Shade and organics','Tree cover can reduce fading while increasing mildew, algae and tannin staining.'),('Drainage paths','Storm water and irrigation can carry sand out of joints along driveway edges and low areas.'),('Patios and pools','Backyard surfaces often stay damp longer than front driveways and need a separate prep plan.')],
'faq':[('Can old sealer simply be covered with a new coat?','Not always. If the remaining coating is failing, incompatible or trapping moisture, adding another layer can worsen appearance. The existing system should be evaluated first.'),('What causes dark joints on Orange Park pavers?','Shade, moisture, organics and irrigation commonly darken joints and surface pores over time. Cleaning should address those conditions before sealing.'),('Do you work on older paver driveways?','Yes. Older driveways are common projects, but the scope depends on joint condition, prior coatings, repairs and how evenly the surface can be restored.'),('Do you seal patios and pool decks too?','Yes. HydroSeal works on suitable driveways, patios, walkways and paver pool decks in the Orange Park service area.')],
'siblings':[('Fleming Island','/service-areas/clay-county/fleming-island'),('Oakleaf Plantation','/service-areas/clay-county/oakleaf-plantation'),('Middleburg','/service-areas/clay-county/middleburg')]
},
{
'path':'service-areas/clay-county/oakleaf-plantation.html','slug':'oakleaf-plantation','parent':'Clay County','parent_url':'/service-areas/clay-county','name':'Oakleaf Plantation','title':'Oakleaf Plantation Paver Sealing | Newer Driveways & Pool Decks | HydroSeal','desc':'Oakleaf Plantation paver sealing for newer builder-installed driveways, patios and pool decks exposed to sun, irrigation, traffic and joint washout.','image':'/assets/hero/oakleaf-plantation-paver-sealing-driveway.webp','layout':'stat','eyebrow':'Oakleaf Plantation • Clay County','h1':'Protect Oakleaf Pavers Before Early Wear Becomes Obvious','intro':'Many Oakleaf Plantation homes have newer builder-installed pavers with open sun exposure, regular irrigation and daily vehicle traffic. Newer does not mean maintenance-free: color can flatten, joints can drop and runoff can create uneven wear before the hardscape looks “old.”','areas':['Oakleaf Plantation','Clay County'],
'features':[('Builder-installed pavers','Early maintenance can protect appearance before sun and traffic create patchy wear.'),('Open sun','Less mature canopy means stronger UV exposure across driveways and front walks.'),('Irrigation','Overspray and runoff can leave mineral marks and move joint sand along edges.'),('Family traffic','Daily vehicle use and frequent outdoor activity can make wear patterns visible faster.')],
'faq':[('Do newer Oakleaf pavers really need sealing?','Newer pavers are still exposed to Florida sun, storms, irrigation and vehicle traffic. Maintenance timing should be based on actual color, joint condition and surface wear rather than home age alone.'),('Why is joint sand disappearing from my Oakleaf driveway?','Storm runoff, irrigation, slopes, repeated washing and daily traffic can lower joint sand over time, especially near edges and drainage paths.'),('Can HydroSeal seal a newer pool deck?','Yes. Suitable paver pool decks can be cleaned and sealed with a moisture-aware plan based on the current condition and surface use.'),('How do I know whether I need cleaning or resealing?','We evaluate contamination, coating wear, joint depth and drainage. Some surfaces primarily need cleaning; others need joint restoration and renewed protection.')],
'siblings':[('Fleming Island','/service-areas/clay-county/fleming-island'),('Orange Park','/service-areas/clay-county/orange-park'),('Middleburg','/service-areas/clay-county/middleburg')]
},
{
'path':'service-areas/clay-county/middleburg.html','slug':'middleburg','parent':'Clay County','parent_url':'/service-areas/clay-county','name':'Middleburg','title':'Middleburg Paver Sealing | Driveways, Patios & Pool Decks | HydroSeal','desc':'Middleburg paver sealing for larger sun-exposed driveways, patios and pool decks with runoff, joint loss, staining and Florida weather wear.','image':'/assets/hero/middleburg-paver-sealing-driveway.png','layout':'editorial','eyebrow':'Middleburg • Clay County','h1':'Paver Sealing for Middleburg’s Larger, More Exposed Properties','intro':'Middleburg projects often involve larger driveways, more open sun, longer drainage paths and properties where storm runoff has room to move across the hardscape. HydroSeal focuses on joint stability, surface preparation and a practical sealing system built around how the property actually drains and gets used.','areas':['Middleburg','Clay County'],
'features':[('Open exposure','Full-sun pavers can lose color and surface protection faster than shaded installations.'),('Long runoff paths','Larger driveways can channel rainwater across slopes and edges, lowering joints over time.'),('Property scale','More square footage makes consistent cleaning, sanding and coverage especially important.'),('Mixed outdoor areas','Driveways, patios, walks and pool surrounds can need different preparation on the same property.')],
'faq':[('Why do Middleburg driveways lose joint sand?','Large surfaces, slopes, Florida downpours, irrigation and repeated washing can move material from joints, especially along edges and drainage routes.'),('Do full-sun pavers need different care?','Open sun can accelerate fading and coating wear. We evaluate actual condition rather than using a fixed maintenance schedule.'),('Can you seal large driveways?','Yes. Larger driveway projects are common, with scope based on cleaning needs, joint depth, repairs, drainage and existing coatings.'),('Do you also seal patios and pool decks in Middleburg?','Yes. HydroSeal works on suitable paver patios, walkways and pool decks as well as driveways.')],
'siblings':[('Fleming Island','/service-areas/clay-county/fleming-island'),('Orange Park','/service-areas/clay-county/orange-park'),('Oakleaf Plantation','/service-areas/clay-county/oakleaf-plantation')]
},
{
'path':'service-areas/st-johns-county/nocatee.html','slug':'nocatee','parent':'St. Johns County','parent_url':'/service-areas/st-johns-county','name':'Nocatee','title':'Nocatee Paver Sealing | Driveways, Pool Decks & Patios | HydroSeal','desc':'Nocatee paver sealing for newer and established driveways, patios and pool decks exposed to strong sun, irrigation, storms and joint-sand wear.','image':'/assets/hero/nocatee-paver-sealing.webp','layout':'stat','eyebrow':'Nocatee • St. Johns County','h1':'Paver Sealing for Nocatee’s High-Visibility Hardscapes','intro':'Nocatee homes often feature large paver driveways, outdoor living areas and pool decks with strong curb-appeal expectations. Open sun, irrigation, summer rain and daily traffic can flatten color and lower joints even when the installation is relatively new.','areas':['Nocatee','St. Johns County'],
'features':[('Newer communities','Modern paver installations still need maintenance based on exposure and joint condition.'),('Strong curb appeal','Large front driveways make uneven color, low joints and staining easy to notice.'),('Pool living','Backyard pool decks need separate moisture and cure planning from the driveway.'),('Irrigation and storms','Frequent water movement can create mineral staining and joint erosion along drainage paths.')],
'faq':[('How often should Nocatee pavers be resealed?','There is no single schedule for every property. Sun, traffic, drainage, irrigation and existing coating condition determine when protection should be renewed.'),('Do newer Nocatee pavers still need joint restoration?','They can. Storms, irrigation, washing and traffic may lower joint sand even on relatively new installations.'),('Can you seal Nocatee pool decks?','Yes. Suitable paver pool decks are prepared with moisture, shade, splash-out and cure conditions in mind.'),('Do you work on driveways and patios too?','Yes. HydroSeal works on suitable paver driveways, patios, walkways and pool decks throughout the Nocatee service area.')],
'siblings':[('Ponte Vedra','/service-areas/st-johns-county/ponte-vedra'),('Ponte Vedra Beach','/service-areas/st-johns-county/ponte-vedra-beach'),('Julington Creek','/service-areas/st-johns-county/julington-creek')]
},
{
'path':'service-areas/st-johns-county/ponte-vedra.html','slug':'ponte-vedra','parent':'St. Johns County','parent_url':'/service-areas/st-johns-county','name':'Ponte Vedra','title':'Ponte Vedra Paver Sealing | Premium Driveways & Pool Decks | HydroSeal','desc':'Ponte Vedra paver sealing for premium driveways, patios and pool decks with sun, irrigation, moisture and joint-sand wear across St. Johns County.','image':'/assets/hero/ponte-vedra-paver-sealing-driveway.webp','layout':'editorial','eyebrow':'Ponte Vedra • St. Johns County','h1':'Precision Paver Sealing for Ponte Vedra Properties','intro':'Ponte Vedra hardscapes often combine large driveways, landscaped entries, outdoor living areas and premium pool environments. The best result comes from evaluating the material, drainage, shade, prior coatings and finish expectations before the sealing system is selected.','areas':['Ponte Vedra','St. Johns County'],
'features':[('Premium driveways','Broad high-visibility surfaces demand even prep, joint depth and sealer coverage.'),('Landscaped entries','Irrigation, fertilizer residue and shaded edges can create staining before the main field looks worn.'),('Outdoor living','Patios and pool surrounds often have different moisture and traffic patterns than the driveway.'),('Previous maintenance','Older coatings and prior reseals need compatibility checks before another system is added.')],
'faq':[('What makes Ponte Vedra paver sealing different?','Large premium hardscapes often combine multiple exposures on one property—open sun, shade, irrigation, pool moisture and previous coatings—so the prep plan must match each surface.'),('Do you seal pool decks in Ponte Vedra?','Yes. HydroSeal works on suitable paver pool decks and evaluates select travertine surfaces separately from concrete pavers.'),('Can you restore joint sand on large driveways?','Yes. When joint restoration is part of the scope, low joints are reset after cleaning with kiln-dried ASTM C144 sand before sealing.'),('What if the driveway has been sealed before?','We evaluate remaining coating condition and compatibility first so the next system is not placed over a failing or unsuitable base.')],
'siblings':[('Nocatee','/service-areas/st-johns-county/nocatee'),('Ponte Vedra Beach','/service-areas/st-johns-county/ponte-vedra-beach'),('Fruit Cove','/service-areas/st-johns-county/fruit-cove')]
},
{
'path':'service-areas/st-johns-county/ponte-vedra-beach.html','slug':'ponte-vedra-beach','parent':'St. Johns County','parent_url':'/service-areas/st-johns-county','name':'Ponte Vedra Beach','title':'Ponte Vedra Beach Paver Sealing | Coastal Driveways & Pool Decks | HydroSeal','desc':'Ponte Vedra Beach paver sealing for coastal driveways, courtyards and pool decks exposed to salt air, humidity, UV, storms and joint washout.','image':'/assets/hero/st-johns-paver-sealing-nocatee-driveway.webp','layout':'cover','eyebrow':'Ponte Vedra Beach • Coastal St. Johns','h1':'Coastal Paver Sealing for Ponte Vedra Beach','intro':'Ponte Vedra Beach pavers face a true coastal mix: salt-laden air, strong UV, wind-driven rain, irrigation, humidity and premium outdoor living spaces. HydroSeal evaluates moisture, surface type, drainage and old coatings before cleaning, restoring joints and applying a compatible sealing system.','areas':['Ponte Vedra Beach','St. Johns County'],
'features':[('Salt-laden air','Coastal exposure adds another stressor to open driveways, courtyards and pool environments.'),('Strong UV','Full-sun pavers can lose color and protection faster than shaded surfaces.'),('Wind-driven rain','Storms can move water and joint sand differently around coastal entries and pool decks.'),('Premium pool areas','Pool decks and natural stone need separate product and moisture decisions from driveways.')],
'faq':[('Does coastal air change how pavers should be sealed?','Coastal humidity, salt-laden air, strong UV and wind-driven rain all affect wear and moisture. The preparation plan should account for the actual property exposure.'),('Do you seal Ponte Vedra Beach pool decks?','Yes. Suitable paver pool decks are common projects, and select travertine surfaces are evaluated separately because stone porosity and finish expectations differ.'),('Should mildew or organic buildup be sealed over?','No. Organic growth and contamination should be removed before sealing so they are not trapped beneath a fresh system.'),('Can older coastal pavers be resealed?','Often, but the existing coating and moisture condition must be evaluated first to determine whether standard resealing is appropriate.')],
'siblings':[('Ponte Vedra','/service-areas/st-johns-county/ponte-vedra'),('Nocatee','/service-areas/st-johns-county/nocatee'),('Julington Creek','/service-areas/st-johns-county/julington-creek')]
},
{
'path':'service-areas/st-johns-county/julington-creek.html','slug':'julington-creek','parent':'St. Johns County','parent_url':'/service-areas/st-johns-county','name':'Julington Creek','title':'Julington Creek Paver Sealing | Driveways & Pool Decks | HydroSeal','desc':'Julington Creek paver sealing for established driveways, patios and pool decks with shade, organic buildup, joint loss and old sealer wear.','image':'/assets/hero/julington-creek-sealing.webp','layout':'split','eyebrow':'Julington Creek • St. Johns County','h1':'Paver Restoration for Established Julington Creek Homes','intro':'Julington Creek combines mature landscaping, established paver installations, busy family driveways and backyard pool areas. Shade can slow fading while increasing moisture and organic buildup, and older surfaces may have previous coatings that need to be evaluated before resealing.','areas':['Julington Creek','St. Johns County'],
'features':[('Established pavers','Older installations may have repairs, prior sealer and uneven joint depth.'),('Tree canopy','Shade can keep patios and driveway edges damp longer, encouraging organic buildup.'),('Family driveways','Daily vehicle traffic and repeated washing can make low joints and worn protection more visible.'),('Pool areas','Screened or shaded pool decks need a moisture-aware preparation plan.')],
'faq':[('Why are Julington Creek pavers darker under trees?','Shade can keep the surface damp longer after rain or irrigation, supporting mildew, algae and tannin staining.'),('Do you handle previously sealed pavers?','Yes. We evaluate the remaining coating first to determine whether the surface is a standard reseal candidate or needs a different restoration path.'),('Can you restore joint sand?','When joint restoration is needed, HydroSeal cleans first and resets low joints with kiln-dried ASTM C144 sand before sealing.'),('Do you seal pool decks in Julington Creek?','Yes. Suitable paver pool decks are prepared and sealed with moisture, shade and cure conditions in mind.')],
'siblings':[('Fruit Cove','/service-areas/st-johns-county/fruit-cove'),('Durbin Crossing','/service-areas/st-johns-county/durbin-crossing'),('Nocatee','/service-areas/st-johns-county/nocatee')]
},
{
'path':'service-areas/st-johns-county/fruit-cove.html','slug':'fruit-cove','parent':'St. Johns County','parent_url':'/service-areas/st-johns-county','name':'Fruit Cove','title':'Fruit Cove Paver Sealing | Shaded Driveways & Pool Decks | HydroSeal','desc':'Fruit Cove paver sealing for shaded driveways, patios and pool decks affected by river humidity, mature trees, leaf staining and moisture.','image':'/assets/hero/fruit-cove-paver-sealing-driveway.webp','layout':'cover','eyebrow':'Fruit Cove • St. Johns County','h1':'Paver Sealing for Fruit Cove’s Shaded, Humid Hardscapes','intro':'Fruit Cove properties often sit among mature trees and river-influenced humidity. Shaded driveways, patios and pool decks can stay damp longer, collect leaf tannins and develop darker joints even when open-sun areas still look good. HydroSeal builds the prep around that uneven exposure.','areas':['Fruit Cove','St. Johns County'],
'features':[('River-area humidity','Higher ambient moisture can slow dry-out on shaded pavers and pool surrounds.'),('Mature trees','Leaf tannins, organic debris and canopy shade often drive the cleaning scope.'),('Mixed sun and shade','One driveway can have bright open sections and dark damp edges that weather differently.'),('Pool and patio zones','Backyard hardscapes may hold moisture longer than front-of-home pavers.')],
'faq':[('Why do Fruit Cove pavers get dark under tree cover?','Shade, humidity, leaf debris and irrigation can keep pavers damp longer and support organic buildup, especially on patios, pool decks and driveway edges.'),('Can leaf stains be cleaned before sealing?','Visible organic staining is addressed during preparation where practical. The goal is to avoid trapping contamination beneath fresh sealer.'),('Do you seal Fruit Cove pool decks?','Yes. Suitable paver pool decks are common projects and receive a moisture-aware preparation plan.'),('What if only part of the driveway looks worn?','Mixed sun, shade and drainage can create uneven wear. We evaluate the whole surface so the recommendation matches the actual condition across the driveway.')],
'siblings':[('Julington Creek','/service-areas/st-johns-county/julington-creek'),('Durbin Crossing','/service-areas/st-johns-county/durbin-crossing'),('Ponte Vedra','/service-areas/st-johns-county/ponte-vedra')]
},
{
'path':'service-areas/st-johns-county/durbin-crossing.html','slug':'durbin-crossing','parent':'St. Johns County','parent_url':'/service-areas/st-johns-county','name':'Durbin Crossing','title':'Durbin Crossing Paver Sealing | Driveways & Pool Decks | HydroSeal','desc':'Durbin Crossing paver sealing for newer family-home driveways, patios and pool decks with sun exposure, runoff, traffic and joint-sand loss.','image':'/assets/hero/durbin-crossing-paver-sealing-driveway.jpeg','layout':'stat','eyebrow':'Durbin Crossing • St. Johns County','h1':'Keep Durbin Crossing Pavers Ahead of Sun, Runoff and Daily Wear','intro':'Durbin Crossing has many newer family homes with visible paver driveways, irrigation, open sun and active outdoor living areas. The most useful maintenance happens before the surface becomes heavily deteriorated—when color starts flattening, joints begin dropping or runoff creates uneven wear.','areas':['Durbin Crossing','St. Johns County'],
'features':[('Newer driveways','Maintenance can begin before the surface looks old or heavily faded.'),('Storm runoff','Water can move joint sand along slopes, driveway edges and drainage paths.'),('Daily traffic','Vehicle use and repeated entry patterns can wear the most visible portions first.'),('Outdoor living','Patios and pool decks need their own moisture and use assessment.')],
'faq':[('Do newer Durbin Crossing pavers need sealing?','Newer pavers are still exposed to strong sun, storms, irrigation and traffic. Maintenance timing should be based on actual surface and joint condition.'),('Why is sand washing out of my driveway joints?','Runoff, irrigation, slopes, washing and traffic can lower joint sand over time, particularly near edges and water paths.'),('Can you seal Durbin Crossing pool decks?','Yes. Suitable paver pool decks can be cleaned and sealed with a scope adjusted for moisture and use.'),('What if the driveway still has good color but low joints?','Joint condition and coating condition are separate issues. We evaluate both before recommending the project scope.')],
'siblings':[('Julington Creek','/service-areas/st-johns-county/julington-creek'),('Fruit Cove','/service-areas/st-johns-county/fruit-cove'),('Nocatee','/service-areas/st-johns-county/nocatee')]
},
{
'path':'service-areas/st-johns-county/trailmark.html','slug':'trailmark','parent':'St. Johns County','parent_url':'/service-areas/st-johns-county','name':'TrailMark','title':'TrailMark Paver Sealing St. Augustine FL | HydroSeal','desc':'TrailMark paver sealing for open-sun driveways, patios and pool areas with irrigation, storms, traffic and joint-sand loss in western St. Johns County.','image':'/assets/hero/paver-sealing-jacksonville-driveway.webp','layout':'editorial','eyebrow':'TrailMark • Western St. Johns County','h1':'Paver Sealing for TrailMark’s Open-Sun Growth Corridor','intro':'TrailMark sits in a newer western St. Johns County environment where paver driveways and outdoor living areas often receive broad sun exposure, regular irrigation and strong summer storm runoff. HydroSeal focuses on early wear, joint stability and a clean maintenance path before the hardscape needs heavier restoration.','areas':['TrailMark','St. Johns County','St. Augustine'],
'features':[('Open sun','Newer landscapes often provide less canopy, leaving pavers exposed to stronger UV for more of the day.'),('Storm drainage','Heavy summer rain can move water and joint material along long driveways and edges.'),('Newer installations','Early maintenance can help preserve uniform appearance before wear becomes patchy.'),('Connected hardscapes','Driveways, entries, patios and pool areas can create a larger maintenance footprint on one property.')],
'faq':[('Do newer TrailMark pavers need professional maintenance?','Yes. Newer surfaces are still affected by sun, storms, irrigation and traffic. Timing should be based on actual wear and joint condition rather than age alone.'),('Can HydroSeal restore joint sand in TrailMark?','When needed, low joints are restored after cleaning with kiln-dried ASTM C144 sand before the sealing step.'),('Do you seal TrailMark patios and pool areas?','Yes. HydroSeal works on suitable paver driveways, patios, walkways and pool areas throughout the TrailMark service area.'),('Why keep this page separate from the St. Johns County page?','TrailMark homeowners have a distinct western St. Johns exposure pattern with newer open-sun hardscapes, irrigation and storm runoff, so the service guidance here is tailored to those property conditions.')],
'siblings':[('Durbin Crossing','/service-areas/st-johns-county/durbin-crossing'),('Julington Creek','/service-areas/st-johns-county/julington-creek'),('Nocatee','/service-areas/st-johns-county/nocatee')]
}
]

SERVICES='''<section class="rg-section"><div class="rg-shell"><span class="rg-eyebrow">Choose the hardscape</span><h2>Match the service to the surface.</h2><div class="rg-services"><a class="rg-card" href="/paver-sealing/driveways"><span>Driveways</span><h3>Driveway paver sealing</h3><p>Cleaning, joint restoration and sealing built around traffic, runoff and curb appeal.</p></a><a class="rg-card" href="/paver-sealing/pool-decks"><span>Pool decks</span><h3>Moisture-aware sealing</h3><p>Pool surfaces need a different prep and cure plan from front-of-home driveways.</p></a><a class="rg-card" href="/paver-sealing/patios-walkways"><span>Outdoor living</span><h3>Patios & walkways</h3><p>Shade, organics and foot traffic often drive the restoration plan in backyard spaces.</p></a><a class="rg-card" href="/paver-sealing/travertine-sealing"><span>Natural stone</span><h3>Travertine sealing</h3><p>Stone is evaluated separately because porosity, moisture and finish expectations differ.</p></a></div></div></section>'''
PROCESS='''<section class="rg-section rg-soft"><div class="rg-shell"><span class="rg-eyebrow">HydroSeal workflow</span><h2>Prep first. Then restore joints. Then seal.</h2><div class="rg-process"><article class="rg-card"><b>01</b><h3>Inspect</h3><p>Evaluate coating condition, staining, drainage, joints and surface use.</p></article><article class="rg-card"><b>02</b><h3>Deep clean</h3><p>Remove organic growth, dirt and problem buildup before fresh sealer is considered.</p></article><article class="rg-card"><b>03</b><h3>Restore joints</h3><p>Where needed, reset low joints with kiln-dried ASTM C144 joint sand.</p></article><article class="rg-card"><b>04</b><h3>Seal correctly</h3><p>Apply a compatible system only after the pavers are properly prepared and ready.</p></article></div><div class="rg-btns"><a class="rg-btn rg-btn--outline" href="/paver-cleaning">Paver Cleaning</a><a class="rg-btn rg-btn--outline" href="/paver-repair">Paver Repair</a><a class="rg-btn rg-btn--outline" href="/paver-resealing">Paver Resealing</a><a class="rg-btn rg-btn--outline" href="/paver-sealing/sand-options">Joint Sand Options</a></div></div></section>'''


def schema(p,url):
    faq=[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in p['faq']]
    graph={'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':'https://hydrosealpavers.com/#website','url':'https://hydrosealpavers.com/','name':'HydroSeal'},{'@type':'WebPage','@id':url+'#webpage','url':url,'name':p['title'],'description':p['desc'],'isPartOf':{'@id':'https://hydrosealpavers.com/#website'}},{'@type':'Service','@id':url+'#service','name':p['title'].replace(' | HydroSeal',''),'serviceType':'Paver sealing, cleaning, joint-sand restoration and hardscape restoration','provider':{'@id':'https://hydrosealpavers.com/#business'},'areaServed':[{'@type':'Place','name':a} for a in p['areas']],'url':url},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':'https://hydrosealpavers.com/'},{'@type':'ListItem','position':2,'name':'Service Areas','item':'https://hydrosealpavers.com/service-areas'},{'@type':'ListItem','position':3,'name':p['parent'],'item':'https://hydrosealpavers.com'+p['parent_url']},{'@type':'ListItem','position':4,'name':p['name'],'item':url}]},{'@type':'FAQPage','@id':url+'#faq','mainEntity':faq}]}
    return json.dumps(graph,ensure_ascii=False)

def feature_cards(p):
    return ''.join(f'<article class="rg-card"><h3>{h}</h3><p>{t}</p></article>' for h,t in p['features'])

def unique_block(p):
    cards=feature_cards(p)
    layout=p['layout']
    if layout=='split':
        return f'''<section class="rg-section"><div class="rg-shell rg-rail"><aside class="rg-card rg-dark-card"><span class="rg-eyebrow" style="color:#9dd9ee;">Local inspection lens</span><h3>What changes the scope here?</h3><div class="rg-checklist"><div>Shade & dry-out</div><div>Joint depth</div><div>Drainage</div><div>Old sealer</div><div>Staining</div><div>Surface use</div></div></aside><div><span class="rg-eyebrow">Local conditions</span><h2>Four things that make {p['name']} paver work different.</h2><div class="rg-stack">{cards}</div></div></div></section>'''
    if layout=='cover':
        return f'''<section class="rg-section"><div class="rg-shell"><span class="rg-eyebrow">Property conditions</span><h2>What we evaluate before sealing in {p['name']}.</h2><p class="rg-lede">A useful restoration plan starts with exposure, moisture, joint stability and whatever coating is already on the pavers.</p><div class="rg-grid-4" style="margin-top:26px;">{cards}</div></div></section>'''
    if layout=='stat':
        return f'''<section class="rg-section"><div class="rg-shell"><span class="rg-eyebrow">Maintenance cycle</span><h2>Catch wear while the surface is still straightforward to restore.</h2><div class="rg-lifecycle"><article><b>Stage 1</b><h3>Color flattens</h3><p>Sun and daily use start changing the surface appearance.</p></article><article><b>Stage 2</b><h3>Joints drop</h3><p>Runoff and washing make low sand more noticeable.</p></article><article><b>Stage 3</b><h3>Staining builds</h3><p>Irrigation and organics increase the prep scope.</p></article><article><b>Stage 4</b><h3>Coating wears unevenly</h3><p>Compatibility becomes more important before resealing.</p></article></div><div class="rg-grid-4" style="margin-top:28px;">{cards}</div></div></section>'''
    return f'''<section class="rg-section"><div class="rg-shell rg-grid-2"><div><span class="rg-eyebrow">Local field notes</span><h2>How {p['name']} conditions change the work.</h2><p class="rg-lede">The best scope is based on what the pavers are doing now—not on a generic calendar or a one-size-fits-all coating.</p><div class="rg-btns"><a class="rg-btn rg-btn--outline" href="/paver-sealing-cost-calculator">Pricing Calculator</a><a class="rg-btn rg-btn--outline" href="/get-a-quote">Request a Quote</a></div></div><div class="rg-stack">{cards}</div></div></section>'''

def hero(p):
    if p['layout']=='cover':
        return f'''<section class="rg-hero-cover"><img src="{p['image']}" alt="{p['name']} paver sealing by HydroSeal" loading="eager" decoding="async" fetchpriority="high"/><div class="rg-shell rg-hero-cover__inner"><div class="rg-hero-panel"><span class="rg-eyebrow" style="color:#9fe5f7;">{p['eyebrow']}</span><h1>{p['h1']}</h1><p>{p['intro']}</p><div class="rg-btns"><a class="rg-btn rg-btn--blue" href="/get-a-quote">Request a Quote</a><a class="rg-btn rg-btn--white" href="tel:+19045375000">Call 904.537.5000</a></div></div></div></section>'''
    if p['layout']=='stat':
        stats=''.join(f'<div><strong>{h}</strong><span>{t}</span></div>' for h,t in p['features'])
        return f'''<section class="rg-hero-stat"><div class="rg-shell rg-hero-stat__grid"><div><span class="rg-eyebrow" style="color:#8bdcf3;">{p['eyebrow']}</span><h1>{p['h1']}</h1><p>{p['intro']}</p><div class="rg-btns"><a class="rg-btn rg-btn--blue" href="/get-a-quote">Request a Quote</a><a class="rg-btn rg-btn--white" href="tel:+19045375000">Call HydroSeal</a></div></div><div class="rg-stat-stack">{stats}</div></div></section>'''
    if p['layout']=='editorial':
        return f'''<section class="rg-hero-editorial"><div class="rg-shell rg-hero-editorial__grid"><div><span class="rg-eyebrow">{p['eyebrow']}</span><h1>{p['h1']}</h1><p class="rg-lede">{p['intro']}</p><div class="rg-btns"><a class="rg-btn rg-btn--blue" href="/get-a-quote">Request a Quote</a><a class="rg-btn rg-btn--outline" href="tel:+19045375000">Call 904.537.5000</a></div></div><div class="rg-photo"><img src="{p['image']}" alt="{p['name']} paver sealing service" loading="eager" decoding="async" fetchpriority="high"/></div></div></section>'''
    return f'''<section class="rg-hero-split"><div class="rg-shell rg-hero-split__grid"><div><span class="rg-eyebrow" style="color:#9fe5f7;">{p['eyebrow']}</span><h1>{p['h1']}</h1><p>{p['intro']}</p><div class="rg-btns"><a class="rg-btn rg-btn--blue" href="/get-a-quote">Request a Quote</a><a class="rg-btn rg-btn--white" href="tel:+19045375000">Call 904.537.5000</a></div></div><div class="rg-photo"><img src="{p['image']}" alt="{p['name']} paver sealing service" loading="eager" decoding="async" fetchpriority="high"/></div></div></section>'''

def proof():
    return '''<div class="rg-shell rg-proof"><div class="rg-proof-grid"><div><strong>Deep Cleaning</strong><span>Preparation before protection</span></div><div><strong>Joint Restoration</strong><span>ASTM C144 kiln-dried sand</span></div><div><strong>Trident Certified</strong><span>Professional sealing systems</span></div><div><strong>2-Year Warranty</strong><span>Workmanship and adhesion</span></div></div></div>'''

def faq_html(p):
    items=''.join(f'<details><summary>{q}</summary><div class="answer">{a}</div></details>' for q,a in p['faq'])
    return f'''<section class="rg-section rg-soft"><div class="rg-shell"><span class="rg-eyebrow">{p['name']} FAQ</span><h2>Questions homeowners ask before sealing.</h2><div class="rg-faq">{items}</div></div></section>'''

def related(p):
    sib=''.join(f'<li><a href="{u}">{n}</a></li>' for n,u in p['siblings'])
    return f'''<section class="rg-section"><div class="rg-shell rg-related"><div class="rg-card"><h3>Nearby Core Areas</h3><ul><li><a href="{p['parent_url']}">{p['parent']}</a></li>{sib}</ul></div><div class="rg-card"><h3>Restoration Services</h3><ul><li><a href="/paver-cleaning">Paver Cleaning</a></li><li><a href="/paver-repair">Paver Repair</a></li><li><a href="/paver-resealing">Paver Resealing</a></li><li><a href="/paver-sealing/sand-options">Joint Sand Options</a></li></ul></div><div class="rg-card"><h3>Planning Guides</h3><ul><li><a href="/learning-center/sealing/what-should-professional-paver-sealing-include">What Professional Sealing Includes</a></li><li><a href="/learning-center/problems/why-is-sand-coming-out-of-my-pavers">Why Joint Sand Comes Out</a></li><li><a href="/paver-sealing-cost-calculator">Pricing Calculator</a></li></ul></div></div></section>'''

def page(p):
    url='https://hydrosealpavers.com/'+p['path'].replace('.html','')
    meta=f'''<!doctype html><html lang="en"><head>{GTAG}<meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="icon" href="/assets/favicons/favicon.ico" sizes="any"/><meta name="theme-color" content="#0F6EA8"/><title>{p['title']}</title><meta name="description" content="{p['desc']}"/><meta name="robots" content="index,follow,max-image-preview:large"/><link rel="canonical" href="{url}"/><meta property="og:type" content="website"/><meta property="og:site_name" content="HydroSeal"/><meta property="og:title" content="{p['title']}"/><meta property="og:description" content="{p['desc']}"/><meta property="og:url" content="{url}"/><meta property="og:image" content="https://hydrosealpavers.com{p['image']}"/><meta name="twitter:card" content="summary_large_image"/><meta name="twitter:title" content="{p['title']}"/><meta name="twitter:description" content="{p['desc']}"/><meta name="twitter:image" content="https://hydrosealpavers.com{p['image']}"/>{CSS}<script type="application/ld+json">{schema(p,url)}</script></head><body><div data-include="/partials/header.html"></div>'''
    body=f'''<main id="page" data-page class="rg-page rg-{p['slug']}">{hero(p)}{proof()}{unique_block(p)}{SERVICES}{PROCESS}<section class="rg-section"><div class="rg-shell"><div class="elfsight-app-bfab489f-7fca-4f05-ba5a-d92616b76b26" data-elfsight-app-lazy></div></div></section>{faq_html(p)}{related(p)}<section class="rg-trust"><div class="rg-shell rg-trust-grid"><div>Licensed & Insured</div><div>Trident Master Certified</div><div>ASTM C144 Joint Sand</div><div>2-Year Workmanship Warranty</div></div></section><section class="rg-final"><div class="rg-shell rg-final-grid"><div><span class="rg-eyebrow" style="color:#8bdcf3;">{p['name']} estimates</span><h2>Find out what your pavers actually need.</h2><p>Send the property address and photos of the driveway, pool deck, patio or walkway. HydroSeal can review the likely cleaning, sanding, repair and sealing scope.</p></div><div class="rg-btns"><a class="rg-btn rg-btn--blue" href="/get-a-quote">Request a Quote</a><a class="rg-btn rg-btn--white" href="tel:+19045375000">Call HydroSeal</a></div></div></section></main>'''
    foot='''<div data-include="/partials/footer.html"></div><script src="/assets/js/include.js" defer></script><script src="/assets/js/router.js" defer></script><script src="/assets/js/nav.js" defer></script><script src="/assets/js/analytics.js" defer></script><script defer src="/assets/js/third-party-loader.js"></script></body></html>'''
    return meta+body+foot

for p in PAGES:
    Path(p['path']).write_text(page(p))
print(f'Rebuilt {len(PAGES)} Clay and St. Johns County child location pages.')
